### ISSUE TITLE
［求］コンフィグでのカスタム機能

### ISSUE THREAD

**Issue by Sakuraga200323** [shmn7iii/Disgot#2]
DiscordおよびMinecraftで送信されるメッセージの形式の、カスタム機能をお願いできないでしょうか。

**Comment by shmn7iii** [comment]
非常に申し訳ないのですが、私の方ですぐに対応することは難しいです。
PR投げていただければマージ対応はいたします。

**FYI**
[saladbowl77](https://github.com/saladbowl77)さんが本レポジトリのfork先で同様の機能を実装なされているのでそちらのご利用を推奨いたします。
当該リリースは[こちら](https://github.com/saladbowl77/Disgot/releases/tag/v1.2)です。
